apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dshthckbv-go 
  janus-idp.io/tekton: dshthckbv-go
  backstage.io/kubernetes-id: dshthckbv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dshthckbv-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml